apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  # echo -n 'postgres' | base64
  postgres-user: cG9zdGdyZXM=
  # echo -n 'yourpassword' | base64
  postgres-password: cGFzc3dvcmQ=
  # echo -n 'workspaces_db' | base64
  postgres-db: d29ya3NwYWNlc19kYg==
